authentication:
  enabled: false
  password: ''
  username: ''
model:
  default: null
paths:
  deepdanbooru: null
  hf_cache: null
  onnx: null
server:
  host: 0.0.0.0
  port: 8083
  reload: false
tagging:
  max_tags_per_category: 1000
  min_tag_score: 0.05